name: Rewrite backstop url
inputs:
  deployed_url:
    description: Deployed domain url (https://zoo.walcron.com)
    required: true
    type: string
  backstop_url:
    description: Override domain url of origin.backstop.json
    default: 'http://localhost:3000'
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Update to vercel deployed branch version
      run: |
        TEST_URL=${{ inputs.deployed_url }}
        DEFAULT_TEST_URL=${{ inputs.backstop_url }}
        sed -i "s|${DEFAULT_TEST_URL}|${TEST_URL}|g" ./scripts/origin.backstop.json
        cat ./scripts/origin.backstop.json
      shell: bash