name: Issue comment workflow

#Only execute on main branches

on:
  issue_comment:
    types: [created]

jobs:
  approve_local_snapshot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: >
      github.event.comment.body == '/update-snapshot' &&
      github.event.issue.pull_request
    steps:
      - name: Snapshot local
        uses: ./.github/workflows/snapshot.yml
        with:
          deployed_url: http://localhost:3000
          test_no_image: false
          pr_checkout: true