name: Issue comment workflow

#Only execute on main branches

on:
  issue_comment:
    types: [created]

jobs:
  approve_local_snapshot:
    permissions:
      pull-requests: write
    if: >
      github.event.comment.body == '/update-snapshot' &&
      github.event.issue.pull_request
    uses: ./.github/workflows/snapshot.yml
    secrets: inherit
    with:
      deployed_url: http://localhost:3000
      test_no_image: false
      pr_checkout: true