name: Validate each branch changes of project

on:
  # run on any push except merge
  push:
    branches-ignore:
      - main
  # for retriggering
  workflow_call:

jobs:
  validate:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/test.yml
  check:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/compliance.yml
  snapshot:
    if: github.ref_protected == false
    permissions:
      pull-requests: write
    uses: ./.github/workflows/snapshot.yml
    secrets: inherit
    with:
      deployed_url: http://localhost:3000
      test_no_image: false
