name: Validate each branch changes of project

on:
  # run on any push except merge
  push:
    branches-ignore:
      - master

jobs:
  validate:
    uses: ./.github/workflows/test.yml
  compliance:
    uses: ./.github/workflows/check_libraries.yml
