name: Push project

on:
  # run on any push
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout
        uses: actions/checkout@v4
      - name: ✅ Verify tests and compilation
        uses: ./.github/actions/validation